name: Deploy Backend to Railway & Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Build the Application
        run: |
          npm run build || echo "No build step defined, skipping"

      - name: Deploy to Railway
        env:
          RAILWAY_DEPLOY_HOOK: ${{ secrets.RAILWAY_DEPLOY_HOOK }}
        run: |
          if [ -n "$RAILWAY_DEPLOY_HOOK" ]; then
            curl -X POST "$RAILWAY_DEPLOY_HOOK"
          else
            echo "RAILWAY_DEPLOY_HOOK is not set, skipping deployment"
          fi

      - name: Deploy to Render (Optional)
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            curl -X POST "$RENDER_DEPLOY_HOOK"
          else
            echo "RENDER_DEPLOY_HOOK is not set, skipping deployment"
          fi

      - name: Test API Health
        run: |
          curl -f https://your-backend-url.com/health || exit 1